# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'  @importFrom Rcpp
#'  @useDynLib aifeducation
NULL

#' @importFrom Rcpp
#' @useDynLib aifeducation
NULL

#' @importFrom Rcpp
#' @useDynLib aifeducation
NULL

#' @importFrom Rcpp
#' @useDynLib aifeducation
NULL

#' @importFrom Rcpp
#' @useDynLib aifeducation
NULL

#' @importFrom Rcpp
#' @useDynLib aifeducation
NULL

#' @importFrom Rcpp
#' @useDynLib aifeducation
NULL

#' @importFrom Rcpp
#' @useDynLib aifeducation
NULL

#' @importFrom Rcpp
#' @useDynLib aifeducation
NULL

#' @importFrom Rcpp
#' @useDynLib aifeducation
NULL

#' @importFrom Rcpp
#' @useDynLib aifeducation
NULL

#' @importFrom Rcpp
#' @useDynLib aifeducation
NULL

#' @importFrom Rcpp
#' @useDynLib aifeducation
NULL

#' @importFrom Rcpp
#' @useDynLib aifeducation
NULL

#' @importFrom Rcpp
#' @useDynLib aifeducation
NULL

#' @importFrom Rcpp
#' @useDynLib aifeducation
NULL

#' @importFrom Rcpp
#' @useDynLib aifeducation
NULL

#' @importFrom Rcpp
#' @useDynLib aifeducation
multi_net_train <- function(input, output, test_input, test_output, output_levels, hidden, learningrate, act_fct, act_fct_last, err_msr_last, freq_recalc_iota2, max_iter, cr_rel_change, cr_abs_error, monitor, patience, return_best, trace) {
    .Call('_aifeducation_multi_net_train', PACKAGE = 'aifeducation', input, output, test_input, test_output, output_levels, hidden, learningrate, act_fct, act_fct_last, err_msr_last, freq_recalc_iota2, max_iter, cr_rel_change, cr_abs_error, monitor, patience, return_best, trace)
}

#' @importFrom Rcpp
#' @useDynLib aifeducation
multi_net_predict_c <- function(wts_list, newdata, act_fct, act_fct_last) {
    .Call('_aifeducation_multi_net_predict_c', PACKAGE = 'aifeducation', wts_list, newdata, act_fct, act_fct_last)
}

