# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @importFrom Rcpp
#' @useDynLib aifeducation, .registration = TRUE
NULL

#' @importFrom Rcpp
#' @useDynLib aifeducation, .registration = TRUE
NULL

#' @importFrom Rcpp
#' @useDynLib aifeducation, .registration = TRUE
NULL

#'-----------------------------------------------------------------------------
NULL

#' @importFrom Rcpp
#' @useDynLib aifeducation, .registration = TRUE
NULL

#' @importFrom Rcpp
#' @useDynLib aifeducation, .registration = TRUE
#' [[Rcpp::export]]
NULL

#' @importFrom Rcpp
#' @useDynLib aifeducation, .registration = TRUE
NULL

#' @importFrom Rcpp
#' @useDynLib aifeducation, .registration = TRUE
NULL

#' @importFrom Rcpp
#' @useDynLib aifeducation, .registration = TRUE
NULL

#' @importFrom Rcpp
#' @useDynLib aifeducation, .registration = TRUE
NULL

#' @importFrom Rcpp
#' @useDynLib aifeducation, .registration = TRUE
NULL

#' @importFrom Rcpp
#' @useDynLib aifeducation, .registration = TRUE
NULL

#' @importFrom Rcpp
#' @useDynLib aifeducation, .registration = TRUE
NULL

#' @importFrom Rcpp
#' @useDynLib aifeducation, .registration = TRUE
NULL

#' @importFrom Rcpp
#' @useDynLib aifeducation, .registration = TRUE
NULL

#' @importFrom Rcpp
#' @useDynLib aifeducation, .registration = TRUE
NULL

#' @importFrom Rcpp
#' @useDynLib aifeducation, .registration = TRUE
NULL

#' @importFrom Rcpp
#' @useDynLib aifeducation, .registration = TRUE
grad_mse <- function(x) {
    .Call(`_aifeducation_grad_mse`, x)
}

#' @importFrom Rcpp
#' @useDynLib aifeducation, .registration = TRUE
grad_tanh <- function(o_k, o_j) {
    .Call(`_aifeducation_grad_tanh`, o_k, o_j)
}

#' @importFrom Rcpp
#' @useDynLib aifeducation, .registration = TRUE
multi_net_train <- function(input, output, test_input, test_output, output_levels, hidden, learningrate, act_fct, act_fct_last, err_msr_last, freq_recalc_iota2, max_iter, cr_rel_change, cr_abs_error, monitor, patience, return_best, trace) {
    .Call(`_aifeducation_multi_net_train`, input, output, test_input, test_output, output_levels, hidden, learningrate, act_fct, act_fct_last, err_msr_last, freq_recalc_iota2, max_iter, cr_rel_change, cr_abs_error, monitor, patience, return_best, trace)
}

#' @importFrom Rcpp
#' @useDynLib aifeducation, .registration = TRUE
multi_net_predict_c <- function(wts_list, newdata, act_fct, act_fct_last) {
    .Call(`_aifeducation_multi_net_predict_c`, wts_list, newdata, act_fct, act_fct_last)
}

