# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'Reshape matrix to array
#'
#'@importFrom Rcpp
#'@useDynLib aifeducation, .registration = TRUE
#'@export
matrix_to_array_c <- function(matrix, times, features) {
    .Call('_aifeducation_matrix_to_array_c', PACKAGE = 'aifeducation', matrix, times, features)
}

